### ISSUE TITLE
i want to contact you for help me

### ISSUE THREAD

**Issue by whynaidu** [hashirahmad/ActivityMoodTracker#1]
please contact me 
https://www.facebook.com/aplocayto

9930454616 whatsapp

**Comment by hashirahmad** [comment]
Sure no problem

I don't have Facebook so best will be here in the Gmail or chat offered by
Google.

Thank you for your time and consideration.
Kind regards

**Comment by whynaidu** [comment]
WHAT IS YOU GMAIL ID 
MY EMAIL ID IS naiduvedant@gmail.com
I WANT YOUR HELP TO RUN THIS PROJECT

**Comment by whynaidu** [comment]
@hashirahmad  please make a contact

**Comment by hashirahmad** [comment]
Check email
